### ISSUE TITLE
Update schedule for 2015-2016

### ISSUE THREAD

**Issue by clarkb7** [clarkb7/Pebble_RPI_Shuttle_Schedule#1]
http://www.rpi.edu/dept/parking/shuttle/eastshuttleschedule.pdf
http://www.rpi.edu/dept/parking/shuttle/westshuttleschedule.pdf

**Comment by kench** [comment]
Would you be interested in building a web service that allows users to edit/update/create schedules in an intuitive and self-service matter and vends this out to various clients (website, phone, watch, etc.) as an RCOS project?
